package com.fishfind.water.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.info.BuildProperties;
import org.springframework.lang.Nullable;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.lang.management.ManagementFactory;
import java.util.LinkedHashMap;
import java.util.Map;

@RestController
public class HealthController {

    private static final long START_TIME = ManagementFactory.getRuntimeMXBean().getStartTime();

    private final String version;

    /**
     * Creates the controller with the version taken from Maven build info, so it can never drift from
     * the pom version the way a hardcoded constant did.
     *
     * @param buildProperties build metadata generated by the spring-boot-maven-plugin {@code build-info}
     *                        goal; may be absent (e.g. IDE runs without a full Maven build)
     */
    @Autowired
    public HealthController(@Nullable BuildProperties buildProperties) {
        this.version = buildProperties == null ? "unknown" : buildProperties.getVersion();
    }

    @GetMapping("/health")
    public Map<String, Object> health() {
        long uptimeSeconds = (System.currentTimeMillis() - START_TIME) / 1000;
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("status", "UP");
        body.put("version", version);
        body.put("uptime", uptimeSeconds);
        return body;
    }
}
