package com.fishfind.weather.config;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Base64;
import java.util.HexFormat;

/**
 * Unwraps individually-encrypted configuration values.
 *
 * <p>A value in a {@code .env} file (or a real environment variable) may be stored as
 * {@code enc:v1:<base64url(nonce || ciphertext || tag)>} instead of plaintext. Anything without that
 * marker is returned untouched, so a partially-encrypted file is valid and the migration can be done
 * one key at a time — and, critically, a service carrying this codec still starts against the old
 * fully-plaintext file.
 *
 * <p><strong>Algorithm:</strong> AES-256-GCM with a 12-byte random nonce and a 128-bit tag. The
 * variable's own name is bound in as additional authenticated data, so a ciphertext lifted from
 * {@code DB_USERNAME} fails to decrypt if pasted over {@code DB_PASSWORD}.
 *
 * <p><strong>Key material</strong> comes from {@code FF_MASTER_KEY_FILE} (a path — preferred, so the
 * key never lands in {@code docker inspect}, shell history, or {@code /proc/self/environ}) or, as a
 * fallback, the raw {@code FF_MASTER_KEY} variable. Either form accepts 32 bytes as hex or base64,
 * with any whitespace ignored.
 *
 * <p>A missing or wrong key when an encrypted value is actually present is a <em>hard startup
 * failure</em>, never a silent pass-through: handing an untouched {@code enc:v1:...} string to the
 * JDBC driver would surface as a baffling login error far from the real cause.
 */
public final class SecretCodec {

    /** Marker identifying an encrypted value; version-tagged so the format can change later. */
    static final String PREFIX = "enc:v1:";

    private static final String KEY_FILE_ENV = "FF_MASTER_KEY_FILE";
    private static final String KEY_ENV = "FF_MASTER_KEY";

    private static final int KEY_BYTES = 32;
    private static final int NONCE_BYTES = 12;
    private static final int TAG_BITS = 128;
    private static final int TAG_BYTES = TAG_BITS / 8;

    /** Cached so a file-backed key is read once per JVM rather than once per value. */
    private static volatile SecretKeySpec cachedKey;

    private SecretCodec() {
    }

    /**
     * Reports whether a value carries the encryption marker.
     *
     * @param value the raw value as read from the dotenv file or environment; may be {@code null}
     * @return {@code true} when the value is an {@code enc:v1:} payload
     */
    public static boolean isEncrypted(String value) {
        return value != null && value.startsWith(PREFIX);
    }

    /**
     * Returns the plaintext for a value, decrypting it when it carries the {@code enc:v1:} marker
     * and returning it verbatim when it does not.
     *
     * @param name  the variable name, bound in as additional authenticated data
     * @param value the raw value
     * @return the plaintext value
     * @throws IllegalStateException when the value is encrypted but no usable key is configured, or
     *                               the payload is malformed, tampered with, or from another key
     */
    public static String decryptIfNeeded(String name, String value) {
        if (!isEncrypted(value)) {
            return value;
        }

        return decryptWith(requireKey(name), name, value);
    }

    /**
     * Decrypts a marked value with an explicitly supplied key.
     *
     * <p>Split out from {@link #decryptIfNeeded} so the cipher can be exercised in tests against a
     * known key and a fixture generated by {@code secret/Protect-Env.ps1}: {@code System.getenv} is
     * immutable within a JVM, so the environment-backed key lookup cannot be driven from a unit test.
     *
     * @param key   the AES key to decrypt with
     * @param name  the variable name, bound in as additional authenticated data
     * @param value the raw {@code enc:v1:} value
     * @return the plaintext value
     * @throws IllegalStateException when the payload is malformed, tampered with, or from another key
     */
    static String decryptWith(SecretKeySpec key, String name, String value) {
        byte[] payload;
        try {
            payload = Base64.getUrlDecoder().decode(value.substring(PREFIX.length()));
        } catch (IllegalArgumentException e) {
            throw new IllegalStateException(
                    "Value of " + name + " is marked " + PREFIX + " but is not valid base64url.", e);
        }

        if (payload.length < NONCE_BYTES + TAG_BYTES) {
            throw new IllegalStateException(
                    "Value of " + name + " is marked " + PREFIX + " but is too short to be a valid payload.");
        }

        byte[] nonce = Arrays.copyOf(payload, NONCE_BYTES);
        byte[] ciphertext = Arrays.copyOfRange(payload, NONCE_BYTES, payload.length);

        try {
            Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(TAG_BITS, nonce));
            cipher.updateAAD(name.getBytes(StandardCharsets.UTF_8));
            return new String(cipher.doFinal(ciphertext), StandardCharsets.UTF_8);
        } catch (Exception e) {
            // Deliberately vague about the cause and silent about the value: a GCM tag failure means
            // wrong key, wrong variable name, or tampering, and distinguishing them helps an attacker.
            throw new IllegalStateException(
                    "Could not decrypt " + name + ". The master key does not match the value, "
                            + "or the value was altered.", e);
        }
    }

    /**
     * Loads and caches the master key.
     *
     * @param name the variable being decrypted, used only to make the failure message actionable
     * @return the AES key
     * @throws IllegalStateException when no key is configured or the material is not 32 bytes
     */
    private static SecretKeySpec requireKey(String name) {
        SecretKeySpec key = cachedKey;
        if (key != null) {
            return key;
        }

        synchronized (SecretCodec.class) {
            if (cachedKey != null) {
                return cachedKey;
            }

            String material = readKeyMaterial();
            if (material == null) {
                throw new IllegalStateException(
                        "Value of " + name + " is encrypted but no master key is configured. Set "
                                + KEY_FILE_ENV + " to the key file path (preferred) or " + KEY_ENV + ".");
            }

            byte[] bytes = decodeKeyMaterial(material);
            if (bytes.length != KEY_BYTES) {
                throw new IllegalStateException(
                        "Master key must be " + KEY_BYTES + " bytes (64 hex chars or 44 base64 chars); got "
                                + bytes.length + " bytes.");
            }

            cachedKey = new SecretKeySpec(bytes, "AES");
            return cachedKey;
        }
    }

    /**
     * Reads key material from the key file when configured, otherwise from the raw environment variable.
     *
     * @return the undecoded key material, or {@code null} when neither source is configured
     */
    private static String readKeyMaterial() {
        String keyFile = System.getenv(KEY_FILE_ENV);
        if (keyFile != null && !keyFile.isBlank()) {
            Path path = Path.of(keyFile.trim());
            try {
                return Files.readString(path, StandardCharsets.UTF_8);
            } catch (Exception e) {
                throw new IllegalStateException(
                        "Could not read the master key file at " + path + " (from " + KEY_FILE_ENV + ").", e);
            }
        }

        String inline = System.getenv(KEY_ENV);
        return inline == null || inline.isBlank() ? null : inline;
    }

    /**
     * Decodes key material given as hex or base64, ignoring whitespace and line breaks so a
     * human-formatted key file works as-is.
     *
     * @param material the raw key text
     * @return the decoded key bytes
     */
    private static byte[] decodeKeyMaterial(String material) {
        String compact = material.replaceAll("\\s", "");
        if (compact.length() == KEY_BYTES * 2 && compact.matches("(?i)[0-9a-f]+")) {
            return HexFormat.of().parseHex(compact);
        }

        try {
            return Base64.getDecoder().decode(compact);
        } catch (IllegalArgumentException e) {
            throw new IllegalStateException(
                    "Master key material is neither " + (KEY_BYTES * 2) + " hex characters nor valid base64.", e);
        }
    }
}
